version: '2.1'

services:
#  udp2raw-icmp:
#    build:
#      context: ./
#    container_name: udp2raw-icmp
#    restart: always
#    privileged: true
#    network_mode: "host"
#    volumes:
#      - ./config/client-icmp.conf:/server.conf

  udp2raw-tcp:
    build:
      context: ./
    container_name: udp2raw-tcp
    restart: always
    privileged: true
    network_mode: "host"
    volumes:
      - ./config/client-tcp.conf:/server.conf

 # udp2raw-tcp6:
 #   build:
 #     context: ./
 #   container_name: udp2raw-tcp6
 #   restart: always
 #   privileged: true
 #   network_mode: "host"
 #   volumes:
 #     - ./config/client-tcp6.conf:/server.conf